### ISSUE TITLE
Raise Error with single atom inputs.

### ISSUE THREAD

**Issue by AkihideHayashi** [pfnet-research/torch-dftd#5]
When the length of atoms is 1, the routine raises error.
```
from ase.build import molecule
from ase.calculators.dftd3 import DFTD3
from torch_dftd.torch_dftd3_calculator import TorchDFTD3Calculator

if __name__ == "__main__":
    atoms = molecule("H")
    # device="cuda:0" for fast GPU computation.
    calc = TorchDFTD3Calculator(atoms=atoms, device="cpu", damping="bj")

    energy = atoms.get_potential_energy()
    forces = atoms.get_forces()

    print(f"energy {energy} eV")
    print(f"forces {forces}")

```

```
Traceback (most recent call last):
  File "quick.py", line 12, in <module>
    energy = atoms.get_potential_energy()
  File "/home/ahayashi/envs/dftd/lib/python3.8/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/ahayashi/envs/dftd/lib/python3.8/site-packages/ase/calculators/calculator.py", line 709, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/ahayashi/torch-dftd/torch_dftd/torch_dftd3_calculator.py", line 141, in get_property
    dftd3_result = Calculator.get_property(self, name, atoms, allow_calculation)
  File "/home/ahayashi/envs/dftd/lib/python3.8/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/ahayashi/torch-dftd/torch_dftd/torch_dftd3_calculator.py", line 119, in calculate
    results = self.dftd_module.calc_energy(**input_dicts, damping=self.damping)[0]
  File "/home/ahayashi/torch-dftd/torch_dftd/nn/base_dftd_module.py", line 75, in calc_energy
    E_disp = self.calc_energy_batch(
  File "/home/ahayashi/torch-dftd/torch_dftd/nn/dftd3_module.py", line 86, in calc_energy_batch
    E_disp = d3_autoev * edisp(
  File "/home/ahayashi/torch-dftd/torch_dftd/functions/dftd3.py", line 189, in edisp
    c6 = _getc6(Zi, Zj, nci, ncj, c6ab=c6ab, k3=k3)  # c6 coefficients
  File "/home/ahayashi/torch-dftd/torch_dftd/functions/dftd3.py", line 97, in _getc6
    k3_rnc = torch.where(cn0 > 0.0, k3 * r, -1.0e20 * torch.ones_like(r)).view(n_edges, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by corochann** [comment]
Resolved by #6
